pipeline:
  test: 
    image: node:7.5.0
    when:
      event: [push,pull_request]
      branches: [master, react-start]
    commands:
      - npm install --silent
      - npm install standard -g
      - npm run test
  deploy:
    image: plugins/ssh
    when:
      event: push
      branch: production
    host: stokkers.no
    port: 22014
    commands:
      - bash /scripts/deploy-viestinta-prod.sh

