pipeline:
  test: 
    image: viestinta/node:viestinta-test
    when:
      event: [push,pull_request]
      branches: [master, react-start]
    environment:
      DATABASE_URL: postgres://postgres:viestintacentos@127.0.0.1:5432
      NODE_ENV: test
    commands:
      - npm install --silent
      - npm install standard -g
      - sleep 10
      - npm start

  deploy:
    image: plugins/ssh
    when:
      event: push
      branch: production
    host: stokkers.no
    port: 22014
    commands:
      - bash /scripts/deploy-viestinta-prod.sh

services:
    postgres:
      image: postgres:9.6
      container_name: viestinta_postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: viestintacentos
        POSTGRES_DB: viestintadb_dev



