FROM node:6-alpine

ENV APP_DIR=/srv/app

RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR

COPY package.json $APP_DIR/package.json

RUN npm install webpack -g
RUN npm install pm2 -g
RUN npm install --silent

COPY . $APP_DIR
RUN webpack

EXPOSE 8000

CMD ["pm2","start","npm","--name viestinta","--","start"]
