version: '3'

services:
  postgres:
    image: postgres:9.6
    container_name: viestinta_postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=viestintacentos
    - POSTGRES_DB=viestintadb_dev
    tty: true
    stdin_open: true
    ports:
    - "5432:5432"
  nodejs:
    build: .
    image: nodetest:viestinta
    links:
    - postgres
    container_name: viestinta_node
    ports:
    - "54321:8000"
    volumes:
    - .:/srv/app/
    - /arv/app/node_modules
    tty: true
    stdin_open: true