version: '2'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.pm2.prod
    image: viestinta:prod
    container_name: viestinta_node
    ports:
    - "54321:8000"
    volumes:
    - .:/srv/app/
    - /arv/app/node_modules
    tty: true
    stdin_open: true
